# Generated by Django 5.2.7 on 2025-10-27 20:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='(no title)', max_length=250, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('begin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان شروع')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('status', models.CharField(choices=[('DO', 'Done'), ('UN', 'Undone')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
