# Generated by Django 5.2.7 on 2025-11-01 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_done', models.BooleanField(default=False, verbose_name='انجام شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='(عنوانی وجود ندارد)', max_length=250, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, default='(توضیحاتی وجود ندارد)', verbose_name='توضیحات')),
                ('begin', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='زمان شروع')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('status', models.CharField(choices=[('DO', 'Done'), ('UN', 'Undone')], default='UN', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['begin'],
                'indexes': [models.Index(fields=['begin'], name='todolist_ev_begin_77378d_idx')],
            },
        ),
    ]
