# Generated by Django 5.2.7 on 2025-10-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DO', 'Done'), ('UN', 'Undone')], default='UN', max_length=2),
        ),
    ]
