# Generated by Django 5.2.7 on 2025-10-29 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['begin']},
        ),
        migrations.AlterField(
            model_name='task',
            name='begin',
            field=models.DateTimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='(توضیحاتی وجود ندارد)', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, default='(عنوانی وجود ندارد)', max_length=250, verbose_name='عنوان'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['begin'], name='todolist_ta_begin_c67191_idx'),
        ),
    ]
