# Generated by Django 5.2.7 on 2025-10-31 06:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_task_options_alter_task_begin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Event',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='todolist_ev_begin_77378d_idx',
            old_name='todolist_ta_begin_c67191_idx',
        ),
    ]
